### ISSUE TITLE
Hope here is the place to post this... no doc for the gain setting.

### ISSUE THREAD

**Issue by iMartyn** [adafruit/Adafruit-Stereo-Speaker-Bonnet-PCB#1]
Following https://learn.adafruit.com/adafruit-speaker-bonnet-for-raspberry-pi makes the hat work, but no information about the gain pads... cut? bridge? etc.

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/pinouts#gain-2-14
has some info - also check the datasheet!

**Comment by iMartyn** [comment]
Perfect, thanks, although fyi gain direct to gnd makes the pi not boot.  I went with the 100k to solve this as I'm fine with the extra gain, but if someone wants that in-between setting, it's a problem. (3b+)
