### ISSUE TITLE
speaker bonnet right / left channel fix

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit-Stereo-Speaker-Bonnet-PCB#3]
The right / left stereo playback works well with a 220k ohm value for R1 connected to SD_MODE. The current 390k results in one side playing both right/left channels.  

The current work around is to [stack a 470k resistor on R1](https://forums.adafruit.com/viewtopic.php?p=1037187#p1037187) to drop the resistance to 220k ohm or swap it. [PR# 2](https://github.com/adafruit/Adafruit-Stereo-Speaker-Bonnet-PCB/pull/2) also mentioned this

Please update the sch / pcb files.

**Comment by BlitzCityDIY** [comment]
added rev D (https://github.com/adafruit/Adafruit-Stereo-Speaker-Bonnet-PCB/commit/7ba780f5f5c00274d3eeb395f444534189f13a0d)

**Comment by mikeysklar** [comment]
Thanks, looks good with 220k R1.
